-------------------------------------------------------------------------------
Test set: io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT
-------------------------------------------------------------------------------
Tests run: 17, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.51 s <<< FAILURE! -- in io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT
io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT.testSimpleTopicIdStrategyFindLatest -- Time elapsed: 0.029 s <<< ERROR!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:437)
	at io.kiota.http.vertx.VertXRequestAdapter.send(VertXRequestAdapter.java:167)
	at io.apicurio.registry.rest.client.groups.item.artifacts.ArtifactsRequestBuilder.post(ArtifactsRequestBuilder.java:130)
	at io.apicurio.tests.ApicurioRegistryBaseIT.createArtifact(ApicurioRegistryBaseIT.java:195)
	at io.apicurio.tests.serdes.apicurio.ProtobufSerdeIT.testSimpleTopicIdStrategyFindLatest(ProtobufSerdeIT.java:73)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.util.concurrent.ExecutionException: io.vertx.core.http.HttpClosedException: Connection was closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.kiota.http.vertx.VertXRequestAdapter.getHttpResponseMessage(VertXRequestAdapter.java:431)
	... 7 more
Caused by: io.vertx.core.http.HttpClosedException: Connection was closed

